name: CoCoTB Functional Coverage
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.6]
  
    env:
      SIM: ghdl

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cocotb-coverage
        pip install cocotb-test
        pip install pytest
        pip install pytest-parallel
        pip install pytest-xdist
    
    
    - uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: llvm

    - run: |
        ghdl --version
        $GHDL --version
    
    - name: regression stretch
      run: |
        cd cocotb_sim/ && make test
    - name: regression debounce
      run: |
        cd cocotb_sim/ && make test_debounce
    - name: regression one_shot
      run: |
        cd cocotb_sim/ && make test_one_shot
    - name: regression_pwm
      run: |
        cd cocotb_sim/ && make test_pwm
      
    - name: Functional Coverage
      run: |
        cd cocotb_sim/ && var1=$(cat coverage_debounce.xml | grep -o -E 'cover_percentage.{0,5}' | head -1 | cut -f2- -d\")
        if [ $var1 = 100 ]; then exit 0; else exit 1; fi
        cd cocotb_sim/ && var2=$(cat coverage_one_shot.xml | grep -o -E 'cover_percentage.{0,5}' | head -1 | cut -f2- -d\")
        if [ $var2 = 100 ]; then exit 0; else exit 1; fi
        cd cocotb_sim/ && var3=$(cat coverage_pwm.xml | grep -o -E 'cover_percentage.{0,5}' | head -1 | cut -f2- -d\")
        if [ $var3 = 100 ]; then exit 0; else exit 1; fi
        cd cocotb_sim/ && var4=$(cat coverage_stretcher.xml | grep -o -E 'cover_percentage.{0,5}' | head -1 | cut -f2- -d\")
        if [ $var4 = 100 ]; then exit 0; else exit 1; fi
